### ISSUE TITLE
The type initializer for 'Confluent.Kafka.Impl.LibRdKafka' threw an exception

### ISSUE THREAD

**Issue by MSDRIOUICH** [ah-/rdkafka-dotnet#118] opened 2017-02-24 14:01 UTC
Hello,
I am using the liberary in my Windows Service VS2015 solution, and its work fine on my devlopement environment under Windows 7 Entreprise .
However, when I install the service ( InstallUtil.exe -i myService.exe, with the same binaries) on my testing server (Windows Server 2008 R2, Framework .net 4.5.2),  I get the following error when trying:" The type initializer for 'Confluent.Kafka.Impl.LibRdKafka' threw an exception" 
Thank you in advance for any suggestions?

**Comment by edenhill** [comment] 2017-02-24 14:19
What Confluent.Kafka version are you using?
We pushed new NuGet packages for Confluent.Kafka and librdkafka.redist yesterday which shouldve fixed a number of linking problems people were seeing.

**Comment by MSDRIOUICH** [comment] 2017-02-24 14:32
I used 0.9.2.0
I am now using the 0.9.4-preview8, I got same probleme.

**Comment by edenhill** [comment] 2017-02-24 14:42
I'm not sure how you package up and deploy your application for target install, but make sure that librdkafka.dll, zlib.dll, etc, are installed along with your application.

**Comment by edenhill** [comment] 2017-02-24 14:46
Please file an issue on https://github.com/confluentinc/confluent-kafka-dotnet and close this one.

**Comment by MSDRIOUICH** [comment] 2017-02-24 14:50
I do have these dlls in folders x86 & x64...
It must be a missing components on my test environment, as the same package is working well on my development machine..

**Closed as completed** 2017-02-24 15:13 UTC

**Comment by edenhill** [comment] 2017-02-24 17:56
@MSDRIOUICH did you find the root cause of the problem?

**Comment by glenthomas** [comment] 2017-03-28 12:20
@edenhill The librdkafka.redist.0.9.4 NuGet package outputs to folders x86 and x64 rather than the application root folder, so the application does not find the required librdkafka DLLs. I assume that this is controlled by the file librdkafka.redist.props. It runs fine in Visual Studio and seems to find the DLLs, but once deployed it can no longer find them in the subfolders. If I copy the files from the x86 folder to my application root it works ok. What is the way best way to handle this?

I am using rdkafka as part of the Confluent dotnet package in a .NET application.

**Comment by glenthomas** [comment] 2017-03-28 12:32
...I have forced the correct files to the root folder using a nuspec file when generating my deployment NuGet package
